name: set_new_password
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.6
  google_fonts: ^4.0.3
  gradient_borders: ^1.0.0
  keyboard_detection: ^0.5.2
  local_hero: ^0.2.0
  lottie: ^2.2.0
  multi_masked_formatter: ^1.0.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
